In [8]:
import numpy as np
from sklearn import preprocessing
#import matplotlib
import matplotlib
import seaborn
import pandas
#Creating a sample data
#input_data=np.array([[3,-1,5, 3,-64], [0,3,-1.3,4.1],[1,2.3, -29,4.3]])
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -
4.3]])

In [10]:
data_standardized=preprocessing.scale(input_data)
print ("\nMean=",data_standardized.mean(axis=0))
print ("\nStd Deviation=",data_standardized.std(axis=0))


Mean= [ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]

Std Deviation= [1. 1. 1. 1.]


In [11]:
#Scaling the random data values to match specified rules
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled=data_scaler.fit_transform(input_data)
print("\nMin Max Scaled Data=", data_scaled)


Min Max Scaled Data= [[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


In [14]:
#Data normalization. Adjusting values in feature vector so as to measure them on a common scale
data_nomalized=preprocessing.normalize(input_data, norm='l1')
print("\nL1 Normalized Data=",data_nomalized)
#Normalization is used to ensure that data points do not get boosted due to the nature of their features.


L1 Normalized Data= [[ 0.21582734 -0.10791367  0.21582734 -0.46043165]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.27619048 -0.40952381]]


In [16]:
#Binarization is used to convert a numerical feature vector into a Boolean vector.
data_binarized=preprocessing.Binarizer(threshold=1.4).transform(input_data)
print("\nBinarized Data=",data_binarized)


Binarized Data= [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]


In [17]:
#One Hot Encoding --used when working with few and scattered numerical values that you may not need to store
encoder=preprocessing.OneHotEncoder()
encoder.fit([[0, 2, 1, 12],[1, 3, 5, 3], [2, 3, 2, 12], [1, 2, 4, 3]])
encoded_vector=encoder.transform([[2, 3, 5, 3]]).toarray()
print("\nEncoded Vector=",encoded_vector)


Encoded Vector= [[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]
